name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app
        run: npm run build -- --base-href /gh-pages-workflow/
      
      - name: Debug directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R dist
          
      - name: Ensure directory exists
        run: |
          if [ ! -d "dist/gh-pages-workflow/browser" ]; then
            echo "Build directory not found!"
            exit 1
          fi
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist/gh-pages-workflow/browser

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v3