name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app
        run: npm run build -- --base-href /gh-pages-workflow/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages-artifact
          path: dist/gh-pages-workflow

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gh-pages-artifact
          path: ./dist
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          path: ./dist/gh-pages-workflow
